version: '3'
services:
  postgres:
    build: database
    image: fast-food-restaurant-database:1.0.0
    ports:
      - "5433:5432"

  backend:
    build: backend
    image: fast-food-restaurant-backend:1.0.0
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=fast_food_restaurant_database
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - JWT_SECRET=8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb1111
      - JWT_ALGORITHM=HS512
      - JWT_ACCESS_EXPIRATION=10
      - JWT_REFRESH_EXPIRATION=60
      - SERVER_PORT=8080
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build: frontend
    image: fast-food-restaurant-frontend:1.0.0
    depends_on:
      - backend
    ports:
      - "3000:3000"