spring:
  application:
    name: fast-food-restaurant-backend
  datasource:
    url: jdbc:postgresql://${DB_HOSTPORT:localhost:5433}/${DB_NAME:fast_food_restaurant_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    secret: ${JWT_SECRET:8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb1111}
    algorithm: ${JWT_ALGORITHM:HS512}
    access-expiration: ${JWT_ACCESS_EXPIRATION:10}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:60}
server:
  port: ${SERVER_PORT:8080}
