spring:
  application:
    name: fast-food-restaurant-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:fast_food_restaurant_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST:smtp.mailersend.net}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:MS_Vi9JUc@trial-0p7kx4xy9xel9yjr.mlsender.net}
    password: ${MAIL_PASSWORD:mmT7k8zw0XGXNSZm}
    protocol: smtp
    sender-email: ${MAIL_SENDER_EMAIL:no-reply@trial-0p7kx4xy9xel9yjr.mlsender.net}
    sender-name: ${MAIL_SENDER_NAME:FastFoodRestaurant}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
security:
  jwt:
    secret: ${JWT_SECRET:8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb1111}
    algorithm: ${JWT_ALGORITHM:HS512}
    access-expiration: ${JWT_ACCESS_EXPIRATION:10}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:60}
server:
  port: ${SERVER_PORT:8080}
